site_name: AIS-catcher Docs
site_description: Comprehensive guide to installing, configuring, and using AIS-catcher.
site_author: jvde.github@gmail.com
site_url: https://aiscatcher.org/docs

theme:
  name: 'material'
  palette:
    # Remove all color schemes except one
    - scheme: default  # This gives you a white background
      primary: white
      accent: white
  logo:   assets/logo.svg 
  language: 'en'
  palette:
    primary: 'blue'
    accent: 'light blue'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  icon:
    repo: fontawesome/brands/github
    social:
      - icon: fontawesome/brands/github
        link: https://github.com/jvde-github/AIS-catcher
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/yourtwitter
  features:
    - navigation.top
    - navigation.expand

repo_url: https://github.com/jvde-github/AIS-catcher
repo_name: GitHub
extra_css:
  - styles/custom.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jvde-github/AIS-catcher
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/yourtwitter

  footer:
    text: '© 2021-2024 jvde.github@gmail.com. All rights reserved.'
    links:
      - title: 'License'
        url: 'license.md'
      - title: 'Disclaimer'
        url: 'disclaimer.md'

nav:
  - Home: index.md
  - Getting Started:
      - Overview: getting-started/overview.md
      - AIS Basics: getting-started/ais-basics.md
  - Installation:
      - Overview: installation/overview.md
      - Docker: installation/docker.md
      - Raspberry Pi: installation/raspberry-pi.md
      - Windows: installation/windows.md
      - Build from Source: installation/build-source.md
      - Ubuntu and Debian: installation/ubuntu-debian.md
  - Basic Usage:
      - Overview: usage/overview.md
      - Web GUI: usage/gui.md
      - Command Line: usage/cli.md
      - JSON Configuration: usage/json-configuration.md
  - Configuration:
      - Overview: configuration/overview.md
      - Input Options:
            - Overview: configuration/input/overview.md
            - SDR Devices:
              - RTL-SDR: configuration/input/rtlsdr.md
              - AirSpy: configuration/input/airspy.md
              - AirSpy HF+: configuration/input/airspyhf.md
              - HackRF: configuration/input/hackrf.md
              - SDRPlay: configuration/input/sdrplay.md
              - SoapySDR: configuration/input/soapysdr.md
            - Network Input:
              - TCP: configuration/input/tcp.md
              - UDP: configuration/input/udp.md
              - SpyServer: configuration/input/spyserver.md
            - File Input:
              - Raw Files: configuration/input/file.md
              - WAV Files: configuration/input/wav.md
            - Other Input:
              - Serial Port: configuration/input/serial.md
              - NMEA2000: configuration/input/NMEA2000.md
      - Model: configuration/model.md
      - Output Options:
        - Overview: configuration/output/overview.md
        - Community Feed: configuration/output/community-feed.md
        - Console Output: configuration/output/console.md
        - Network Output:
          - TCP Server: configuration/output/TCP-server.md
          - TCP Client: configuration/output/TCP-client.md
          - UDP: configuration/output/UDP.md
          - HTTP: configuration/output/HTTP.md
        - Web Viewer: configuration/output/web-viewer.md
        - MQTT Integration: configuration/output/MQTT.md
        - NMEA2000: configuration/output/NMEA2000.md
        - Postgres: configuration/output/PSQL.md
  - Advanced:
      - Advanced Configuration: advanced/advanced-configuration.md
      - Grafana: advanced/grafana.md
      - Validation: advanced/validation.md
      - Troubleshooting: advanced/troubleshooting.md
      - JSON AIS format: advanced/JSON-decoding.md
  - Community: community.md
  - FAQ: faq.md
  - References: references.md

markdown_extensions:
  - toc:
      permalink: true      
  - tables
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.keys
  - attr_list
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

plugins:
  - search
  - awesome-pages
