name: Deploy MkDocs Site

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install Dependencies
        run: |
          pip install \
            mkdocs-material \
            mkdocs-material-extensions \
            mkdocs-glightbox \
            mkdocs-git-revision-date-localized-plugin \
            pillow \
            cairosvg \
            mkdocs-minify-plugin \
            mkdocs-redirects \
            mkdocs-rss-plugin
      
      - name: Build Site
        run: mkdocs build
      
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
