name: Deploy MkDocs Material Documentation

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install dependencies
        run: |
          pip install \
            mkdocs-material \
            mkdocs-material-extensions \
            mkdocs-glightbox \
            mkdocs-git-revision-date-localized-plugin \
            pillow \
            cairosvg \
            mkdocs-minify-plugin \
            mkdocs-redirects \
            mkdocs-rss-plugin

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build site
        run: mkdocs build

      - name: Upload artifact
        uses: actions/upload-pages-artifa
